extends Node

enum PORTRAITS_BB {NORMAL, SQUINT, SHADOW, SMILE, UPSET, CHILL, DISAPPOINTED, JOKING, SURPRISED, SIGH}

enum PORTRAITS_PHYLLIS {NORMAL, GRRR, HAPPY, SCOLD, DEVIOUS, DOWN, SCREAM, WORRIED, DREAMING, SAD}

enum PORTRAITS_SAM {NORMAL, SAD, COCKY, THINKING, MAD, SMUG, CONCERN, EXCITED, SLEEPY, SERIOUS}
